name: Angular — Frontend

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./staff_frontend_processing
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ${{env.working-directory}} 

    - name: Run tests
      run: npm run test:headless
      working-directory: ${{env.working-directory}} 

    - name: Build
      run: npm run build:prod
      working-directory: ${{env.working-directory}} 
